use [diplomDb]


INSERT INTO LICENSECLASSES VALUES('A');
INSERT INTO LICENSECLASSES VALUES('B');
INSERT INTO LICENSECLASSES VALUES('C');
INSERT INTO LICENSECLASSES VALUES('D');
INSERT INTO LICENSECLASSES VALUES('E');
INSERT INTO LICENSECLASSES VALUES('M1');
INSERT INTO LICENSECLASSES VALUES('A1');
INSERT INTO LICENSECLASSES VALUES('B1');
INSERT INTO LICENSECLASSES VALUES('C1');
INSERT INTO LICENSECLASSES VALUES('D1');
INSERT INTO LICENSECLASSES VALUES('BE');
INSERT INTO LICENSECLASSES VALUES('CE');
INSERT INTO LICENSECLASSES VALUES('DE');

INSERT INTO DRIVERLICENSE VALUES('Нет прав','','');
INSERT INTO DRIVERLICENSE VALUES('99 30 121341','10.01.2014','10.01.2024');
INSERT INTO DRIVERLICENSE VALUES('99 71 221363','15.03.2017','15.03.2027');
INSERT INTO DRIVERLICENSE VALUES('99 87 412590','20.11.2015','20.11.2025');
INSERT INTO DRIVERLICENSE VALUES('99 56 256734','11.06.2014','11.06.2024');

INSERT INTO DRIVERLICENSECLASS VALUES(1,2);
INSERT INTO DRIVERLICENSECLASS VALUES(1,3);
INSERT INTO DRIVERLICENSECLASS VALUES(1,4);
INSERT INTO DRIVERLICENSECLASS VALUES(1,5);
INSERT INTO DRIVERLICENSECLASS VALUES(2,2);
INSERT INTO DRIVERLICENSECLASS VALUES(2,3);
INSERT INTO DRIVERLICENSECLASS VALUES(3,2);
INSERT INTO DRIVERLICENSECLASS VALUES(3,3);

INSERT INTO ORG VALUES('АО Объединенная двигателестроительная корпорация','РФ','105118','г.Москва','пр.Буденного д.16');

INSERT INTO DEPARTMENTS VALUES('Информационный отдел',1);
INSERT INTO DEPARTMENTS VALUES('Сетевой отдел',1);
INSERT INTO DEPARTMENTS VALUES('Транспортный отдел',1);
INSERT INTO DEPARTMENTS VALUES('Ремонтный отдел',1);
INSERT INTO DEPARTMENTS VALUES('Совет директоров',1);
INSERT INTO Departments VALUES('Отдел кадров',1)

INSERT INTO PERSONAL VALUES(1000,'Лобников А.А.','Генеральный директор',5,45,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1001,'Ронинов П.И.','Генеральный директор',5,48,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1002,'Шишкин П.М.','Начальник отдела',1,37,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1003,'Хомяков Н.Е.','Начальник отдела',2,34,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1004,'Никитин А.Г.','Начальник отдела',3,36,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1005,'Титников Т.Н.','Начальник отдела',4,39,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1006,'Рокин П.У.','Начальник отдела',5,32,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1007,'Шиконов К.Н.','Начальник отдела',6,41,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1008,'Григорьев А.А.','Водитель',3,41,'М',2,1,0,0,0,0);
INSERT INTO PERSONAL VALUES(1009,'Логинов А.В.','Водитель',3,43,'М',3,1,0,0,0,0);
INSERT INTO PERSONAL VALUES(1010,'Паролев П.Б.','Водитель',3,39,'М',4,1,0,0,0,0);
INSERT INTO PERSONAL VALUES(1011,'Канунникова З.С.','Диспетчер',3,31,'Ж',1,0,1,0,0,0);
INSERT INTO PERSONAL VALUES(1012,'Володина А.С.','Диспетчер',3,34,'Ж',1,0,1,0,0,0);
INSERT INTO PERSONAL VALUES(1013,'Дорохов Б.Н.','Системный администратор',2,27,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1014,'Головин Н.Е.','Программист',1,29,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1015,'Пряников Г.М.','Программист',1,31,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1016,'Абрамов Н.Г.','Системный администратор',2,23,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1017,'Григорян Р.Г.','Главный инженер',4,38,'М',1,0,0,0,0,1);
INSERT INTO PERSONAL VALUES(1018,'Исламов М.А.','Инженер',4,31,'М',1,0,0,0,0,1);
INSERT INTO PERSONAL VALUES(1019,'Попов Б.В.','Менеджер по персоналу',6,26,'М',1,0,0,0,1,0);
INSERT INTO PERSONAL VALUES(1020,'Ибрагимова Н.В.','Заведующая бюро пропусков',6,42,'Ж',1,0,0,0,1,0);
INSERT INTO PERSONAL VALUES(9999,'Червов Н.Е.','Администратор',1,20,'М',1,0,0,1,0,0);
INSERT INTO PERSONAL VALUES(1110,'Шнобелев К.В.','Водитель',3,39,'М',5,1,0,0,0,0);


--INSERT INTO DRIVERS VALUES(9,1);
--INSERT INTO DRIVERS VALUES(10,2);
--INSERT INTO DRIVERS VALUES(11,3);

--INSERT INTO DISPATCHERS VALUES(10);
--INSERT INTO DISPATCHERS VALUES(11);

INSERT INTO AUTH VALUES(1,'lob','123');
INSERT INTO AUTH VALUES(2,'ron','123');
INSERT INTO AUTH VALUES(3,'shi','123');
INSERT INTO AUTH VALUES(4,'hom','123');
INSERT INTO AUTH VALUES(5,'nik','123');
INSERT INTO AUTH VALUES(6,'tit','123');
INSERT INTO AUTH VALUES(7,'rok','123');
INSERT INTO AUTH VALUES(8,'shk','123');
INSERT INTO AUTH VALUES(9,'gri','123');
INSERT INTO AUTH VALUES(10,'log','123');
INSERT INTO AUTH VALUES(11,'par','123');
INSERT INTO AUTH VALUES(12,'kan','123');
INSERT INTO AUTH VALUES(13,'vol','123');
INSERT INTO AUTH VALUES(14,'dor','123');
INSERT INTO AUTH VALUES(15,'gol','123');
INSERT INTO AUTH VALUES(16,'pra','123');
INSERT INTO AUTH VALUES(17,'abr','123');
INSERT INTO AUTH VALUES(18,'grig','123');
INSERT INTO AUTH VALUES(19,'isl','123');
INSERT INTO AUTH VALUES(20,'pop','123');
INSERT INTO AUTH VALUES(21,'ibr','123');
INSERT INTO AUTH VALUES(22,'adm','123');

--INSERT INTO PERSONALSDEPARTMENTS VALUES(1,5);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(2,5);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(3,1);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(4,2);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(5,3);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(6,4);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(7,3);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(8,3);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(9,3);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(10,3);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(11,3);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(12,2);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(13,1);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(14,1);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(15,2);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(16,4);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(17,4);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(18,6);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(19,6);
--INSERT INTO PERSONALSDEPARTMENTS VALUES(20,1);

INSERT INTO MesTypes VALUES('Пригородный');
INSERT INTO MesTypes VALUES('Междугородний');

INSERT INTO TransTypes VALUES('Для собственный нужд');
INSERT INTO TransTypes VALUES('Для служебных нужд')

INSERT INTO TsTypes VALUES('Бензоновый');
INSERT INTO TsTypes VALUES('Дизельный');
INSERT INTO TsTypes VALUES('Электрический');
INSERT INTO TsTypes VALUES('Гибридный');

INSERT INTO TsStatus VALUES('В ремонте');
INSERT INTO TsStatus VALUES('Свободен');
INSERT INTO TsStatus VALUES('Занят');

INSERT INTO Photos values('/Images/camry.png','Toyota Camry');
INSERT INTO Photos values('/Images/gaz.png','Газель');
INSERT INTO Photos values('/Images/gaznext.png','Газель Некст');
INSERT INTO Photos values('/Images/kamaz.png','Камаз');
INSERT INTO Photos values('/Images/lexus.png','Lexus LX 500');
INSERT INTO Photos values('/Images/kamazGal.png','Камаз Галичанин');
INSERT INTO Photos values('/Images/scania.png','Scania');
INSERT INTO Photos values('/Images/liaz.png','Лиаз 5256');
INSERT INTO Photos values('/Images/fordTransit.png','Ford Transit');
INSERT INTO Photos values('/Images/noPhoto.png','Нет фото');


INSERT INTO Transport VALUES('ХВ349Н777','Toyota Camry (ХВ349Н777)',1,2,'/Images/camry.png');
INSERT INTO Transport VALUES('ЛГ122Г50','Камаз (ЛГ122Г50)',2,2,'/Images/kamaz.png');
INSERT INTO Transport VALUES('ОО777О777','Lexus LX 500 (ОО777О777)',1,3,'/Images/lexus.png');
INSERT INTO Transport VALUES('НЕ371Г70','Газель (НЕ371Г70)',1,1,'/Images/gaz.png');
INSERT INTO Transport VALUES('ШН421К170','Камаз Галичанин (ШН421К170)',2,2,'/Images/kamazGal.png');
INSERT INTO Transport VALUES('ТГ155Л170','Газель Некст (ТГ155Л170)',1,2,'/Images/gaznext.png');
INSERT INTO Transport VALUES('ПК601Н90','Scania (ПК601Н90)',2,2,'/Images/scania.png');
INSERT INTO Transport VALUES('ОК952К777','Лиаз 5256 (ОК952К777)',2,2,'/Images/liaz.png');
INSERT INTO Transport VALUES('КК101Н777','Ford Transit (КК101Н777)',1,2,'/Images/fordTransit.png');














