//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoLog.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAutoLogEntities : DbContext
    {
        public dbAutoLogEntities()
            : base("name=dbAutoLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<TransportStatus> TransportStatus { get; set; }
        public virtual DbSet<TransportTypes> TransportTypes { get; set; }
    }
}
