//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoLog.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLicenseClass
    {
        public int id { get; set; }
        public int licenseId { get; set; }
        public int classId { get; set; }
    
        public virtual DriverLicense DriverLicense { get; set; }
        public virtual LicenseClasses LicenseClasses { get; set; }
    }
}
