//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoLog.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Auth = new HashSet<Auth>();
            this.Waybillses = new HashSet<Waybillses>();
            this.Waybillses1 = new HashSet<Waybillses>();
            this.Waybillses2 = new HashSet<Waybillses>();
        }
    
        public int id { get; set; }
        public int tabNumber { get; set; }
        public string FIO { get; set; }
        public string position { get; set; }
        public int departmentId { get; set; }
        public int age { get; set; }
        public string pol { get; set; }
        public int idVU { get; set; }
        public bool isDri { get; set; }
        public bool isDis { get; set; }
        public bool isAdm { get; set; }
        public bool isPer { get; set; }
        public bool isSer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auth> Auth { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual DriverLicense DriverLicense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waybillses> Waybillses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waybillses> Waybillses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waybillses> Waybillses2 { get; set; }
    }
}
