//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoLog.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transport()
        {
            this.Waybillses = new HashSet<Waybillses>();
        }
    
        public int id { get; set; }
        public string GovNumber { get; set; }
        public string tsModel { get; set; }
        public int tsTypeId { get; set; }
        public int tsStatusId { get; set; }
        public string Photo { get; set; }
    
        public virtual Photos Photos { get; set; }
        public virtual TsStatus TsStatus { get; set; }
        public virtual TsTypes TsTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Waybillses> Waybillses { get; set; }
    }
}
