//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoLog.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int TransportTypeId { get; set; }
        public int DepartmentsId { get; set; }
        public int StatusId { get; set; }
        public string GovNumber { get; set; }
        public string VinNumber { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual TransportTypes TransportTypes { get; set; }
        public virtual TransportStatus TransportStatus { get; set; }
    }
}
