//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoLog.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tsLogDbEntities : DbContext
    {
        public tsLogDbEntities()
            : base("name=tsLogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DriverLicense> DriverLicense { get; set; }
        public virtual DbSet<DriverLicenseClass> DriverLicenseClass { get; set; }
        public virtual DbSet<LicenseClasses> LicenseClasses { get; set; }
        public virtual DbSet<MesTypes> MesTypes { get; set; }
        public virtual DbSet<org> org { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<TransTypes> TransTypes { get; set; }
        public virtual DbSet<TsStatus> TsStatus { get; set; }
        public virtual DbSet<TsTypes> TsTypes { get; set; }
        public virtual DbSet<Waybillses> Waybillses { get; set; }
    }
}
