//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace avtoLog.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waybillses
    {
        public int nom { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int mesTypeId { get; set; }
        public int transTypeId { get; set; }
        public int idDis { get; set; }
        public int idCus { get; set; }
        public int transportId { get; set; }
        public int orgId { get; set; }
        public string routee { get; set; }
        public int idDri { get; set; }
    
        public virtual MesTypes MesTypes { get; set; }
        public virtual org org { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Personal Personal1 { get; set; }
        public virtual Personal Personal2 { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual TransTypes TransTypes { get; set; }
    }
}
